title: AI Safety Project
description: TBD
baseurl: "/AI-Safety-Project"

navigation:
  - title: Home
    url: /
    order: 1
  - title: Methodology
    url: /methodology
    order: 2
  - title: Evaluation
    url: /evaluation
    order: 3
  - title: Results
    url: /results
    order: 4
  - title: Discussions
    url: /discussions
    order: 5
  - title: Conclusions
    url: /conclusions
    order: 6
  - title: Code
    url: /code
    order: 7

collections:
  pages:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
