# Ensure all files are processed
exclude: []
include: ['_pages']
permalink: /:title/

# Other existing configurations...
title: AI Safety Project
description: TBD

# Add this line to set the base URL
baseurl: "/AI-Safety-Project"

navigation:
  - title: Home
    url: /
  - title: Methodology
    url: /methodology
  - title: Evaluation
    url: /evaluation
  - title: Results
    url: /results
  - title: Code
    url: /code
  - title: Conclusions
    url: /conclusions

collections:
  pages:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Add these lines for additional debugging
verbose: true
profile: true
    
