title: Evaluating LLM Safety for Youth
description: AI Safety Course Project
baseurl: "/AI-Safety-Project"

navigation:
  - title: Home
    url: /
    order: 1
  - title: Related_Works
    url: /relatedworks
    order: 2
  - title: Methodology
    url: /methodology
    order: 3
  - title: Evaluation
    url: /evaluation
    order: 4
  - title: Results
    url: /results
    order: 5
  - title: Discussions
    url: /discussions
    order: 6
  - title: Conclusions
    url: /conclusions
    order: 7
  - title: Code
    url: /code
    order: 8
  - title: Afterword
    url: /afterword
    order: 9

collections:
  pages:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
