# Ensure all files are processed
exclude: []
include: ['_pages']
permalink: /:title/

# Other existing configurations...
title: AI Safety Project
description: TBD

# Add this line to set the base URL
baseurl: "/AI-Safety-Project"

navigation:
  - title: Home
    url: /
    order: 1
  - title: Methodology
    url: /methodology/
    order: 2
  - title: Evaluation
    url: /evaluation/
    order: 3
  - title: Results
    url: /results/
    order: 4
  - title: Code
    url: /code/
    order: 5
  - title: Conclusions
    url: /conclusions/
    order: 6

collections:
  pages:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Add these lines for additional debugging
verbose: true
profile: true
    
